### ISSUE TITLE
LICENSE missing

### ISSUE THREAD

**Issue by tvlc** [lvsti/mapscale#3]
Could you please add license to your code? Without license it cannot be further used by others, see 
https://help.github.com/articles/open-source-licensing/

Here is simple guideline how to add license: https://github.com/blog/1530-choosing-an-open-source-license

**Comment by lvsti** [comment]
I set the license to MIT: https://github.com/lvsti/mapscale/commit/ffb7b3cafe3d0ea28eb7ed14daa4d3aba5878268

I'm surprised that anyone would still want to use this long-abandoned and obsolete project, but there you go. :)

**Comment by tvlc** [comment]
Thank you! Still good basis to start with :)
